<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="../css/ol.css" />
<link rel="stylesheet" href="../css/layerswitcher.css" />
<link rel="stylesheet" href="../css/climate.css" />
<script type="text/javascript" src="../../js/jquery-2.2.4.min.js"></script>
<script type="text/javascript" src="../js/ol.js"></script>
<script type="text/javascript" src="../js/layerswitcher.js"></script>
<script type="text/javascript" src="../js/graticule.js"></script>
<script type="text/javascript" src="../js/compass.js"></script>
